### ISSUE TITLE
Horizontal positioning of a TikZ Picture with a fitted frame in a right-to-left polygossia document doesn't work as expected

### ISSUE THREAD

**Issue by EvanAad** [kvafa/bidi#14] opened 2022-11-12 10:44 UTC
## Brief outline of the issue

A right-to-left document containing a wide TikZ picture with a fitted node (i.e. a node using the "fit" option from the "fit" TikZ library) cannot be displaced to the left if the displacement pushes the node beyond the text margin.

## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [+] Links to <tex.stackexchange.com> discussion if appropriate: https://tex.stackexchange.com/q/664833/21685
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

\documentclass{article}
\usepackage{lipsum,tikz}
\usetikzlibrary{fit}

\usepackage[RTLdocument]{bidi}

\begin{document}
    \lipsum[1-1]
    
    \noindent\hspace{0cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};
    
    \noindent\hspace{3cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};
\end{document}

## Expected behavior
The lower rectangle should be set 3cm to the left of the text's right margin.

**Comment by kvafa** [comment] 2022-11-13 10:38
Thanks for your bug report. I have not had time to look into tikz fit library but I have experimented with your minimal example a  bit.

If you start with something like 

````tex
\noindent\hspace{3cm}\tikz \node [ draw, fit={(0,0) (0,1)} ] {};
````

and change `(0,1)` incrementally to `(1,1)`, `(2,1)`, `(6,1)`, etc, you will see that your rectangles moves to the left which is the expected behavior. However, when you reach `(9,1)` your rectangle stop moving to the left and for `(10,1)`, your rectangle enalrges horizontally to the right not to the left. The horizontal `9` is where your right text margin is.

Please give me a couple of days so that I can investigate this. I am currently at the middle of something else but will definitely get back to you in few days with an answer.

**Comment by EvanAad** [comment] 2022-11-14 07:08
Thanks for your reply and attention.

**Comment by kvafa** [comment] 2022-11-15 08:34
I have looked into this and it seems to be a limitation of the TeX--XeT algorithm that XeTeX uses via e-TeX. To see the issue independent of tikz, please see the following minimal example:

````tex
\documentclass{article}
\usepackage[RTLdocument]{bidi}
\begin{document}
\noindent\hbox{This horizontal box should contain enough text so that
its width is the same a}

\noindent\hspace{3cm}\hbox{This horizontal box should contain}

\noindent\hspace{3cm}\hbox{This horizontal box should contain enough text so that}

\noindent\hspace{3cm}\hbox{This horizontal box should contain enough text so that
its width is the same a}
\end{document}
````
where you should see the same behavior. As this is an engine bug/limitation, I am afraid that there is not much I can do here. However, if you just want to get the same output, something like the following should do the trick.

````tex
\documentclass{article}
\usepackage{lipsum,tikz}
\usetikzlibrary{fit}

\usepackage[RTLdocument]{bidi}

\begin{document}
\lipsum[1-1]

\noindent\hspace{0cm}\tikz \node [ draw, fit={(0,0) (12,1)} ] {};

\moveleft\dimexpr3cm-\parindent\relax\hbox{\tikz \node [ draw, fit={(0,0) (12,1)} ] {};}
\end{document}
````
Please note that I certainly acknowledge that this is a bug but as it is the engine issue, I do not think there is much that I can do at the level of the bidi package. Sorry!

**Closed by kvafa** 2022-11-15 08:34 UTC
Labels: bug, wontfix, engine

**Comment by kvafa** [comment] 2022-11-15 08:52
I have updated my reply above with an alternative workaround.

**Comment by EvanAad** [comment] 2022-11-15 09:10
Thank you for your attention and prompt response, your insight, the simpler
demonstrating code, and the workaround. I have submitted a bug report with
the e-TeX project using your simplified demonstrating example.

**Comment by kvafa** [comment] 2022-11-15 09:19
That is the pleasure. The original author of e-TeX passed away several years ago sadly and I think it is quite unlikely that this gets fixed any time soon if at all. The workarounds that I suggested are not too bad so I think they should work.

**Comment by EvanAad** [comment] 2022-11-15 14:02
Sorry to hear. Thanks for letting me know.

**Comment by EvanAad** [comment] 2022-11-18 07:41
I'd like to let you know that I've received an email from Laurence Finston,
a member of the e-TeX bug report mailing list. He wrote the following:

> I don't believe that it is a bug in e-tex.  Please see the attached TeX
and PDF files.  I believe that the result is the expected (and desired)
one.  The commands are:
> etex ttemp.tex
> dvipdfmx ttemp.dvi
> I'm sorry, but I can't help you with LaTeX, because I don't use it.  I
hope this helps, anyway.

I attach the two files he attached to his message.

I don't understand the details of his code, but by looking at the resulting
PDF file my sense is that his code does not test the bug, since it doesn't
push the hboxes beyond the text area into the margin, which is the
circumstance under which the bug manifests in your code (which I used to
report the bug to the e-TeX project) as well as in my original code.

**Comment by EvanAad** [comment] 2022-11-18 08:30
After communicating my critique to Mr. Finston, he replied as follows. (I
attach the PDF file he attached to his message.)

> My guess is that the glue for the indentation has a shrink component so
that it will shrink in order to prevent an overfull box.  If true, then the
indentation is present, it's just doesn't have much if any width.  Somebody
familiar with LaTeX would have to give a definitive answer.

> For what it's worth, the following code demonstrates that one can put an
hbox anywhere one wants with respect to the margins in right-to-left mode
using etex (see attachment):

%% ttemp.tex

\special{papersize=297mm, 210mm} %% DIN A4
\hsize=297mm
\vsize=210mm

\advance\hoffset by -1in
\advance\voffset by -1in

\advance\hoffset by 1cm
\advance\voffset by 1cm

\advance\hsize by -2cm

\parindent=0pt

\TeXXeTstate=1

\beginR
\vbox{\line{\hskip3em The quick brown fox jumps over the lazy dog.  The
quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.\hss}\vskip.5\baselineskip
\line{\hskip-3em The quick brown fox jumps over the lazy dog.  The quick
brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.\hss}\vskip.5\baselineskip
\line{\hskip10em The quick brown fox jumps over the lazy dog.  The quick
brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.\hss}\vskip.5\baselineskip
\line{\hskip-10em The quick brown fox jumps over the lazy dog.  The quick
brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.\hss}\vskip.5\baselineskip
\line{\hskip30em The quick brown fox jumps over the lazy dog.  The quick
brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.\hss}\vskip.5\baselineskip
\line{\hskip-30em The quick brown fox jumps over the lazy dog.  The quick
brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.\hss}}
\endR

\bye

**Comment by EvanAad** [comment] 2022-11-18 08:46
I've received another message from Mr. Finstone, in which he concedes that
there is an issue, but he seems not to deem it a bug in e-TeX. Rather he
puts the onus of resolving the issue on the users of the e-TeX package.
Following is his message. Should I report this issue to the XeTeX project?
Could they implement a solution.

> I've tested this a little more and discovered that \parindent and \beginR
... \leftR don't work well together.
> With the following example, if you set, e.g., \parindent=1cm, you get an
overfull box in the second block of text.

> Depending on what you want, it may be advisable to put the r-to-l text in
a vbox.  In the first block, the last, incomplete line is typeset flush
left, not flush right.  In the second block, it is flush right, which is
probably the desired behavior.

> If one wants indentation, it's best to put explicit glue at the beginning
of a paragraph or line in r-to-l mode, i.e., a skip or a kern.
> It would seem that r-to-l mode is really designed for short passages
within l-to-r text and not for full paragraphs or multiple paragraphs.
> It can be used for those things, but it takes a little extra work.

> \beginR
> The quick brown fox jumps over the lazy dog.  The quick brown fox jumps
over the lazy dog.
> The quick brown fox jumps over the lazy dog.  The quick brown fox jumps
over the lazy dog.
> The quick brown fox jumps over the lazy dog.  The quick brown fox jumps
over the lazy dog.
> \endR

> \vskip1cm

> \beginR
> \vbox{\leavevmode The quick brown fox jumps over the lazy dog.  The quick
brown fox jumps over the lazy dog.
> The quick brown fox jumps over the lazy dog.  The quick brown fox jumps
over the lazy dog.
> The quick brown fox jumps over the lazy dog.  The quick brown fox jumps
over the lazy dog.
> }
> \endR

**Comment by kvafa** [comment] 2022-11-18 09:14
Thanks Evan. I am not familiar with Laurence but from what you have posted so far it seems to me that he does not understand the issue; the issue is not that we can not place an `\hbox` wherever we like but explicitly the one demonstrated in my code above. Sure, we can place an `\hbox` wherever we want to place as shown in my two other solutions but he entirely misses the point. I am also a Plain TeX user and do not use LaTeX. All he had to do was to apply the content of the minimal example I provided in right to left in Plain TeX and see the issue for himself.

Having said that, I was in contact with Peter Breitenlohner, the original author of e-TeX several years ago when he was still alive and we discussed several issues including this one. He agreed back then that this was a limitation of TeX--XeT algorithm in e-TeX and that it could be a feature since `\beginL`, `\endL`, `\beginR`, and `\endR` are all horizontal primitives. We agreed that this could be fixed and Peter said that he will work on it but sadly he passed away and things were not fixed. In fact, if you look at TeXLive commits, you can see some of the history of our discussions.

**Comment by kvafa** [comment] 2022-11-18 09:33
[This commit](https://tug.org/svn/texlive/trunk/Build/source/texk/web2c/etexdir/etex.ch?r1=29312&r2=32197)
shows the first issue raised by me and that Peter fixed it. [This commit](https://tug.org/svn/texlive/trunk/Build/source/texk/web2c/etexdir/etex.ch?r1=29248&r2=29250) and [this commit](https://tug.org/svn/texlive/trunk/Build/source/texk/web2c/etexdir/etex.ch?r1=29250&r2=29312) shows that Peter was trying to fix the issue of reversing whatsits in right to left but he did not complete it. Although, these do not show the particular issue in question, it can show some history of the discussions of issues between me and him.

**Comment by EvanAad** [comment] 2022-11-18 09:46
Thank you very much for your input. Yes, if you could show some relevant
history of the discussions between you and Mr. Breitenlohner, I'll add them
to my e-TeX bug report.

Having said that, the facts that Mr. Breitenlohner has passed away, and
that the folks on the e-TeX mailing list seem slow at grasping the issues
at hand (and even if they did grasp it perfectly, I don't know what use it
would be, since they may not be developers, but merely users of e-TeX),
have convinced me to switch from polyglossia+xelatex to babel+lualatex,
both of which are actively developed and maintained, and the babel
developer is very energetically involved in some TeX forums.

**Comment by EvanAad** [comment] 2022-11-18 10:55
I'll take this into consideration. I appreciate your responses greatly.

**Comment by Udi-Fogiel** [comment] 2023-04-26 10:49
@EvanAad  I think that the problem is actually that text in overfull `\hbox` flows to the right, independent from the current paragraph or text direction.

The example that you gave is a bit misleading, as what is flowing to the right margin is the space added by `\hspace{3cm}` and you don't see it. 

For example, consider the following document

```Latex
\documentclass{article}

\usepackage[
	RTLdocument
]{bidi}

\begin{document}
	\noindent\hbox{a really long text a really long text a really long text a really long text a really long text a really long text a really long text a really long text a really long text a really long text a really long text a really long text}
\end{document}
```

If you will comment `RTLdocuement` you will notice how the text is flowing right in all cases. you can produce the same effect without an explicit `\hbox`, with just a "hard to break" line. for example

```Latex
\documentclass{article}
\usepackage[
	RTLdocument
]{bidi}

\begin{document}
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
	aaaaaaaaaaaaaaaaa%
\end{document}
```
